<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>reporting-bi-service-secrets</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ReportingBI.Application\ReportingBI.Application.csproj" />
    <ProjectReference Include="..\ReportingBI.Infrastructure\ReportingBI.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\..\shared\auth-library\Shared.Auth.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.8" />
  </ItemGroup>
</Project>
