version: '3.8'

services:
  mobile-field-app:
    container_name: agri-mobile-field-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped
