apiVersion: v1
kind: ConfigMap
metadata:
  name: agri-global-config
  namespace: agriculture-erp
data:
  RABBITMQ_HOST: "rabbitmq.agriculture-erp.svc.cluster.local"
  POSTGRES_HOST: "postgres.agriculture-erp.svc.cluster.local"
  POSTGRES_PORT: "5432"
